SRC = $(wildcard *.c)
OBJ = $(patsubst %.c, ../$(ODIR)/%.o, $(SRC))

ifdef DEBUG
	CFLAGS += -g -DDEBUG
else
	CFLAGS += -O3
endif

.PHONY: all build

all: build

../$(ODIR)/%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

../$(TARGET): $(OBJ)
	$(CC) $(CFLAGS) $(LIBS) -o $@ $^

build: ../$(TARGET)
